// <auto-generated />
using backend.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701000000_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
    }
}
